/*
 * world_a.c — World A: The Verdant Expanse (ROM tile data, 9 × 25600 bytes).
 *
 * Tile IDs (from tile.h):
 *   0=GRASS  1=DIRT  2=WATER  3=TREE  4=ROCK
 *   5=TILLED 6=CROP_1 7=CROP_2 8=CROP_3
 *   9=LAVA   10=ICE   11=CORRUPTION
 *
 * Each section is 160 rows × 160 columns = 25600 bytes.
 * Row macros expand to exactly 160 comma-separated u8 values.
 * Row 0 and row 159 are tree borders.  Rows 1–158 (158 rows) are interior.
 */

#include "world_a.h"

/* Tile shorthands */
#define G 0   /* GRASS */
#define D 1   /* DIRT  */
#define W 2   /* WATER */
#define T 3   /* TREE  */
#define R 4   /* ROCK  */

/* ---- Row templates (160 values each) ------------------------------------ */

/* Solid tree border */
#define TREE_ROW \
    T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,\
    T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,\
    T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,\
    T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,\
    T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,\
    T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,\
    T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,\
    T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T

/* Open grass (left and right column stay as border trees) */
#define GRASS_ROW \
    T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T

/* Grass with scattered tree clusters */
#define GRASS_TREE_ROW \
    T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    T,T,T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    T,T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T

/* Grass with rock outcrops */
#define GRASS_ROCK_ROW \
    T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    R,R,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,R,R,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T

/* Grass with mixed trees and rocks */
#define GRASS_MIX_ROW \
    T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,T,T,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,R,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T,T,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T

/* Grass with a dirt path */
#define GRASS_DIRT_ROW \
    T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T

/* Small water pond for section 5 (water strip across mid-row) */
#define POND_ROW \
    T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,W,W,W,W,W,W,W,W,G,G,\
    G,G,G,G,G,G,G,G,G,G,W,W,W,W,W,W,W,W,G,G,\
    G,G,G,G,G,G,G,G,G,G,W,W,W,W,W,W,W,W,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T

/*
 * Helper: emit N repetitions of a row macro.
 * We use explicit repetition to avoid variadic macro tricks that some
 * compilers reject under strict C89/C99 modes.
 */

/* =========================================================================
 * Section 1 — Northwest: heavy forest, scattered rocks
 * 1 border + 158 interior + 1 border = 160 rows
 * Interior pattern: 158 rows in groups cycling over 4 types.
 * 158 = 39×4 + 2, so 39 full cycles + 2 extra.
 * ========================================================================= */
const u8 world_a_section1[160 * 160] = {
    TREE_ROW,                                    /* row   0 */
    /* 39 × 4 = 156 interior rows (rows 1–156) */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW,  /* 1-4   */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 5-8   */
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /* 9-12  */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /* 13-16 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 17-20 */
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /* 21-24 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /* 25-28 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 29-32 */
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /* 33-36 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /* 37-40 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 41-44 */
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /* 45-48 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /* 49-52 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 53-56 */
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /* 57-60 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /* 61-64 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 65-68 */
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /* 69-72 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /* 73-76 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 77-80 */
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /* 81-84 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /* 85-88 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 89-92 */
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /* 93-96 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /* 97-100*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /*101-104*/
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /*105-108*/
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /*109-112*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /*113-116*/
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /*117-120*/
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /*121-124*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /*125-128*/
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /*129-132*/
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /*133-136*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /*137-140*/
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /*141-144*/
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /*145-148*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /*149-152*/
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /*153-156*/
    /* 2 extra rows (rows 157-158) */
    GRASS_TREE_ROW, GRASS_MIX_ROW,                                   /*157-158*/
    TREE_ROW                                     /* row 159 */
};

/* =========================================================================
 * Section 2 — North-centre: open grass with rock outcrops
 * ========================================================================= */
const u8 world_a_section2[160 * 160] = {
    TREE_ROW,
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*  1-4  */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*  5-8  */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*  9-12 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 13-16 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 17-20 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 21-24 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 25-28 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 29-32 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 33-36 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 37-40 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 41-44 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 45-48 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 49-52 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 53-56 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 57-60 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 61-64 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 65-68 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 69-72 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 73-76 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 77-80 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 81-84 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 85-88 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 89-92 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 93-96 */
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 97-100*/
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*101-104*/
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*105-108*/
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*109-112*/
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*113-116*/
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*117-120*/
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*121-124*/
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*125-128*/
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*129-132*/
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*133-136*/
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*137-140*/
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*141-144*/
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*145-148*/
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*149-152*/
    GRASS_ROW,      GRASS_ROCK_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*153-156*/
    GRASS_ROW,      GRASS_ROCK_ROW,                                  /*157-158*/
    TREE_ROW
};

/* =========================================================================
 * Section 3 — Northeast: cycling trees, mix, rocks
 * ========================================================================= */
const u8 world_a_section3[160 * 160] = {
    TREE_ROW,
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /*  1-4  */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /*  5-8  */
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /*  9-12 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /* 13-16 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 17-20 */
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /* 21-24 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /* 25-28 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 29-32 */
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /* 33-36 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /* 37-40 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 41-44 */
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /* 45-48 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /* 49-52 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 53-56 */
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /* 57-60 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /* 61-64 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 65-68 */
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /* 69-72 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /* 73-76 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 77-80 */
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /* 81-84 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /* 85-88 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 89-92 */
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /* 93-96 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /* 97-100*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /*101-104*/
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /*105-108*/
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /*109-112*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /*113-116*/
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /*117-120*/
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /*121-124*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /*125-128*/
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /*129-132*/
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /*133-136*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /*137-140*/
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /*141-144*/
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, /*145-148*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /*149-152*/
    GRASS_ROCK_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_ROCK_ROW, /*153-156*/
    GRASS_TREE_ROW, GRASS_MIX_ROW,                                   /*157-158*/
    TREE_ROW
};

/* =========================================================================
 * Section 4 — West: grass, trees, dirt paths
 * ========================================================================= */
const u8 world_a_section4[160 * 160] = {
    TREE_ROW,
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /*  1-4  */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /*  5-8  */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /*  9-12 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 13-16 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 17-20 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 21-24 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 25-28 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 29-32 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 33-36 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 37-40 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 41-44 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 45-48 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 49-52 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 53-56 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 57-60 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 61-64 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 65-68 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 69-72 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 73-76 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 77-80 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 81-84 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 85-88 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 89-92 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 93-96 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /* 97-100*/
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /*101-104*/
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /*105-108*/
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /*109-112*/
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /*113-116*/
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /*117-120*/
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /*121-124*/
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /*125-128*/
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /*129-132*/
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /*133-136*/
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /*137-140*/
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /*141-144*/
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /*145-148*/
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /*149-152*/
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_DIRT_ROW, GRASS_MIX_ROW,  /*153-156*/
    GRASS_ROW,      GRASS_TREE_ROW,                                  /*157-158*/
    TREE_ROW
};

/* =========================================================================
 * Section 5 — Centre: player spawn zone, open clearing with small pond.
 * Interior rows 1–158:
 *   rows  1–60:  open grass (60 rows)
 *   rows 61–66:  pond rows  (6 rows)
 *   rows 67–158: open grass (92 rows)
 *   Total interior = 60 + 6 + 92 = 158. Correct.
 * ========================================================================= */
const u8 world_a_section5[160 * 160] = {
    TREE_ROW,                                                         /* row 0 */
    /* rows 1-60: open grass (60 rows = 15 groups of 4) */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /*  1-4  */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /*  5-8  */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /*  9-12 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 13-16 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 17-20 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 21-24 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 25-28 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 29-32 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 33-36 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 37-40 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 41-44 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 45-48 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 49-52 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 53-56 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 57-60 */
    /* rows 61-66: pond (6 rows) */
    POND_ROW, POND_ROW, POND_ROW, POND_ROW, POND_ROW, POND_ROW,
    /* rows 67-158: open grass (92 rows = 23 groups of 4) */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 67-70  */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 71-74  */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 75-78  */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 79-82  */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 83-86  */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 87-90  */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 91-94  */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 95-98  */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /* 99-102 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /*103-106 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /*107-110 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /*111-114 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /*115-118 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /*119-122 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /*123-126 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /*127-130 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /*131-134 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /*135-138 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /*139-142 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /*143-146 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /*147-150 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /*151-154 */
    GRASS_ROW, GRASS_ROW, GRASS_ROW, GRASS_ROW,  /*155-158 */
    TREE_ROW                                                          /* row 159 */
};

/* =========================================================================
 * Section 6 — East: mix, rocks, grass, trees
 * ========================================================================= */
const u8 world_a_section6[160 * 160] = {
    TREE_ROW,
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*  1-4  */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*  5-8  */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*  9-12 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 13-16 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 17-20 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 21-24 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 25-28 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 29-32 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 33-36 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 37-40 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 41-44 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 45-48 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 49-52 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 53-56 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 57-60 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 61-64 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 65-68 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 69-72 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 73-76 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 77-80 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 81-84 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 85-88 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 89-92 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 93-96 */
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 97-100*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*101-104*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*105-108*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*109-112*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*113-116*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*117-120*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*121-124*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*125-128*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*129-132*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*133-136*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*137-140*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*141-144*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*145-148*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*149-152*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*153-156*/
    GRASS_MIX_ROW,  GRASS_ROCK_ROW,                                  /*157-158*/
    TREE_ROW
};

/* =========================================================================
 * Section 7 — Southwest: grass with dirt trails
 * ========================================================================= */
const u8 world_a_section7[160 * 160] = {
    TREE_ROW,
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, /*  1-4  */
    GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      /*  5-8  */
    GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*  9-12 */
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, /* 13-16 */
    GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      /* 17-20 */
    GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 21-24 */
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, /* 25-28 */
    GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      /* 29-32 */
    GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 33-36 */
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, /* 37-40 */
    GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      /* 41-44 */
    GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 45-48 */
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, /* 49-52 */
    GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      /* 53-56 */
    GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 57-60 */
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, /* 61-64 */
    GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      /* 65-68 */
    GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 69-72 */
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, /* 73-76 */
    GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      /* 77-80 */
    GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 81-84 */
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, /* 85-88 */
    GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      /* 89-92 */
    GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /* 93-96 */
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, /* 97-100*/
    GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      /*101-104*/
    GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*105-108*/
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, /*109-112*/
    GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      /*113-116*/
    GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*117-120*/
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, /*121-124*/
    GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      /*125-128*/
    GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*129-132*/
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, /*133-136*/
    GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      /*137-140*/
    GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*141-144*/
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, /*145-148*/
    GRASS_ROW,      GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      /*149-152*/
    GRASS_MIX_ROW,  GRASS_DIRT_ROW, GRASS_ROW,      GRASS_MIX_ROW,  /*153-156*/
    GRASS_DIRT_ROW, GRASS_ROW,                                       /*157-158*/
    TREE_ROW
};

/* =========================================================================
 * Section 8 — South-centre: rotating 4-type terrain pattern
 * ========================================================================= */
const u8 world_a_section8[160 * 160] = {
    TREE_ROW,
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_ROCK_ROW, GRASS_DIRT_ROW, /*  1-4  */
    GRASS_TREE_ROW, GRASS_ROCK_ROW, GRASS_DIRT_ROW, GRASS_ROW,      /*  5-8  */
    GRASS_ROCK_ROW, GRASS_DIRT_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*  9-12 */
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_TREE_ROW, GRASS_ROCK_ROW, /* 13-16 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_ROCK_ROW, GRASS_DIRT_ROW, /* 17-20 */
    GRASS_TREE_ROW, GRASS_ROCK_ROW, GRASS_DIRT_ROW, GRASS_ROW,      /* 21-24 */
    GRASS_ROCK_ROW, GRASS_DIRT_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 25-28 */
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_TREE_ROW, GRASS_ROCK_ROW, /* 29-32 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_ROCK_ROW, GRASS_DIRT_ROW, /* 33-36 */
    GRASS_TREE_ROW, GRASS_ROCK_ROW, GRASS_DIRT_ROW, GRASS_ROW,      /* 37-40 */
    GRASS_ROCK_ROW, GRASS_DIRT_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 41-44 */
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_TREE_ROW, GRASS_ROCK_ROW, /* 45-48 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_ROCK_ROW, GRASS_DIRT_ROW, /* 49-52 */
    GRASS_TREE_ROW, GRASS_ROCK_ROW, GRASS_DIRT_ROW, GRASS_ROW,      /* 53-56 */
    GRASS_ROCK_ROW, GRASS_DIRT_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 57-60 */
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_TREE_ROW, GRASS_ROCK_ROW, /* 61-64 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_ROCK_ROW, GRASS_DIRT_ROW, /* 65-68 */
    GRASS_TREE_ROW, GRASS_ROCK_ROW, GRASS_DIRT_ROW, GRASS_ROW,      /* 69-72 */
    GRASS_ROCK_ROW, GRASS_DIRT_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 73-76 */
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_TREE_ROW, GRASS_ROCK_ROW, /* 77-80 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_ROCK_ROW, GRASS_DIRT_ROW, /* 81-84 */
    GRASS_TREE_ROW, GRASS_ROCK_ROW, GRASS_DIRT_ROW, GRASS_ROW,      /* 85-88 */
    GRASS_ROCK_ROW, GRASS_DIRT_ROW, GRASS_ROW,      GRASS_TREE_ROW, /* 89-92 */
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_TREE_ROW, GRASS_ROCK_ROW, /* 93-96 */
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_ROCK_ROW, GRASS_DIRT_ROW, /* 97-100*/
    GRASS_TREE_ROW, GRASS_ROCK_ROW, GRASS_DIRT_ROW, GRASS_ROW,      /*101-104*/
    GRASS_ROCK_ROW, GRASS_DIRT_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*105-108*/
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_TREE_ROW, GRASS_ROCK_ROW, /*109-112*/
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_ROCK_ROW, GRASS_DIRT_ROW, /*113-116*/
    GRASS_TREE_ROW, GRASS_ROCK_ROW, GRASS_DIRT_ROW, GRASS_ROW,      /*117-120*/
    GRASS_ROCK_ROW, GRASS_DIRT_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*121-124*/
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_TREE_ROW, GRASS_ROCK_ROW, /*125-128*/
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_ROCK_ROW, GRASS_DIRT_ROW, /*129-132*/
    GRASS_TREE_ROW, GRASS_ROCK_ROW, GRASS_DIRT_ROW, GRASS_ROW,      /*133-136*/
    GRASS_ROCK_ROW, GRASS_DIRT_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*137-140*/
    GRASS_DIRT_ROW, GRASS_ROW,      GRASS_TREE_ROW, GRASS_ROCK_ROW, /*141-144*/
    GRASS_ROW,      GRASS_TREE_ROW, GRASS_ROCK_ROW, GRASS_DIRT_ROW, /*145-148*/
    GRASS_TREE_ROW, GRASS_ROCK_ROW, GRASS_DIRT_ROW, GRASS_ROW,      /*149-152*/
    GRASS_ROCK_ROW, GRASS_DIRT_ROW, GRASS_ROW,      GRASS_TREE_ROW, /*153-156*/
    GRASS_DIRT_ROW, GRASS_ROW,                                       /*157-158*/
    TREE_ROW
};

/* =========================================================================
 * Section 9 — Southeast: dense forest
 * ========================================================================= */
const u8 world_a_section9[160 * 160] = {
    TREE_ROW,
    GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, /*  1-4  */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, /*  5-8  */
    GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /*  9-12 */
    GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, /* 13-16 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, /* 17-20 */
    GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 21-24 */
    GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, /* 25-28 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, /* 29-32 */
    GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 33-36 */
    GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, /* 37-40 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, /* 41-44 */
    GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 45-48 */
    GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, /* 49-52 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, /* 53-56 */
    GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 57-60 */
    GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, /* 61-64 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, /* 65-68 */
    GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 69-72 */
    GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, /* 73-76 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, /* 77-80 */
    GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 81-84 */
    GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, /* 85-88 */
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, /* 89-92 */
    GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /* 93-96 */
    GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, /* 97-100*/
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, /*101-104*/
    GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /*105-108*/
    GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, /*109-112*/
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, /*113-116*/
    GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /*117-120*/
    GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, /*121-124*/
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, /*125-128*/
    GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /*129-132*/
    GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, /*133-136*/
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, /*137-140*/
    GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /*141-144*/
    GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, /*145-148*/
    GRASS_TREE_ROW, GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, /*149-152*/
    GRASS_MIX_ROW,  GRASS_TREE_ROW, GRASS_TREE_ROW, GRASS_MIX_ROW,  /*153-156*/
    GRASS_TREE_ROW, GRASS_TREE_ROW,                                  /*157-158*/
    TREE_ROW
};

#undef G
#undef D
#undef W
#undef T
#undef R
