/*
 * world_b.c — World B: Shattered Isles (ROM tile data, 9 × 25600 bytes).
 *
 * Tile IDs:
 *   0=GRASS  1=DIRT  2=WATER  3=TREE  4=ROCK
 *   5=TILLED 6=CROP_1 7=CROP_2 8=CROP_3
 *   9=LAVA   10=ICE   11=CORRUPTION
 *
 * Theme: heavy water presence, grass islands, dirt paths, rock outcrops.
 * Section 5 (centre): Tidecrypt sanctum entrance — ROCK ring in the middle.
 *
 * All sections: 160 rows × 160 cols = 25600 bytes.
 * Interior: rows 1–158 (158 rows). Border rows 0 and 159 = TREE_ROW.
 * Cycle: 39 groups of 4 rows = 156 rows, plus 2 extra = 158. Total OK.
 */

#include "world_b.h"

#define G 0   /* GRASS */
#define D 1   /* DIRT  */
#define W 2   /* WATER */
#define T 3   /* TREE  */
#define R 4   /* ROCK  */

/* ---- Row templates (160 values each) ------------------------------------ */

/* Tree border */
#define TREE_ROW \
    T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,\
    T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,\
    T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,\
    T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,\
    T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,\
    T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,\
    T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,\
    T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T

/* Large water channel — most of the row is water */
#define WATER_WIDE_ROW \
    T,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,\
    W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,\
    W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,\
    W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,\
    W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,\
    W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,\
    W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,\
    W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,T

/* Grass island in a sea of water */
#define ISLAND_ROW \
    T,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,\
    W,W,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,W,W,\
    W,W,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,W,W,\
    W,W,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,W,W,\
    W,W,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,W,W,\
    W,W,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,W,W,\
    W,W,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,W,W,\
    W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,T

/* Grass row with water on both sides (coastal strip) */
#define COASTAL_ROW \
    T,W,W,W,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,W,W,W,T

/* Dirt path across water (bridge/causeway) */
#define CAUSEWAY_ROW \
    T,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,\
    W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,\
    D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,\
    D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,\
    W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,\
    W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,\
    W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,\
    W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,T

/* Grass with rocks (beach/rocky shore) */
#define SHORE_ROCK_ROW \
    T,W,W,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    R,R,R,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,R,R,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,W,W,T

/* Open grass strip between water areas */
#define GRASS_STRIP_ROW \
    T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T

/* Rock ring row for section 5 sanctum entrance */
#define SANCTUM_ROW \
    T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,\
    G,G,G,G,G,G,G,R,R,R,R,R,R,R,R,R,R,G,G,G,\
    G,G,G,G,G,G,G,R,G,G,G,G,G,G,G,G,R,G,G,G,\
    G,G,G,G,G,G,G,R,G,G,G,G,G,G,G,G,R,G,G,G,\
    G,G,G,G,G,G,G,R,R,R,R,R,R,R,R,R,R,G,G,G,\
    G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T

/* =========================================================================
 * Section 1 — NW island: large water area, grass island
 * ========================================================================= */
const u8 world_b_section1[160 * 160] = {
    TREE_ROW,
    WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, /*  1-4  */
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, /*  5-8  */
    ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     /*  9-12 */
    WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, /* 13-16 */
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, /* 17-20 */
    ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     /* 21-24 */
    WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, /* 25-28 */
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, /* 29-32 */
    ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     /* 33-36 */
    WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, /* 37-40 */
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, /* 41-44 */
    ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     /* 45-48 */
    WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, /* 49-52 */
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, /* 53-56 */
    ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     /* 57-60 */
    WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, /* 61-64 */
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, /* 65-68 */
    ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     /* 69-72 */
    WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, /* 73-76 */
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, /* 77-80 */
    ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     /* 81-84 */
    WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, /* 85-88 */
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, /* 89-92 */
    ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     /* 93-96 */
    WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, /* 97-100*/
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, /*101-104*/
    ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     /*105-108*/
    WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, /*109-112*/
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, /*113-116*/
    ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     /*117-120*/
    WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, /*121-124*/
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, /*125-128*/
    ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     /*129-132*/
    WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, /*133-136*/
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, /*137-140*/
    ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     /*141-144*/
    WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, /*145-148*/
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, /*149-152*/
    ISLAND_ROW,     WATER_WIDE_ROW, WATER_WIDE_ROW, ISLAND_ROW,     /*153-156*/
    WATER_WIDE_ROW, WATER_WIDE_ROW,                                  /*157-158*/
    TREE_ROW
};

/* =========================================================================
 * Section 2 — N coastal: grass coast with water strips
 * ========================================================================= */
const u8 world_b_section2[160 * 160] = {
    TREE_ROW,
    COASTAL_ROW,    GRASS_STRIP_ROW, CAUSEWAY_ROW,   COASTAL_ROW,    /*  1-4  */
    GRASS_STRIP_ROW,CAUSEWAY_ROW,    COASTAL_ROW,    GRASS_STRIP_ROW,/*  5-8  */
    CAUSEWAY_ROW,   COASTAL_ROW,     GRASS_STRIP_ROW,CAUSEWAY_ROW,   /*  9-12 */
    COASTAL_ROW,    GRASS_STRIP_ROW, CAUSEWAY_ROW,   COASTAL_ROW,    /* 13-16 */
    GRASS_STRIP_ROW,CAUSEWAY_ROW,    COASTAL_ROW,    GRASS_STRIP_ROW,/* 17-20 */
    CAUSEWAY_ROW,   COASTAL_ROW,     GRASS_STRIP_ROW,CAUSEWAY_ROW,   /* 21-24 */
    COASTAL_ROW,    GRASS_STRIP_ROW, CAUSEWAY_ROW,   COASTAL_ROW,    /* 25-28 */
    GRASS_STRIP_ROW,CAUSEWAY_ROW,    COASTAL_ROW,    GRASS_STRIP_ROW,/* 29-32 */
    CAUSEWAY_ROW,   COASTAL_ROW,     GRASS_STRIP_ROW,CAUSEWAY_ROW,   /* 33-36 */
    COASTAL_ROW,    GRASS_STRIP_ROW, CAUSEWAY_ROW,   COASTAL_ROW,    /* 37-40 */
    GRASS_STRIP_ROW,CAUSEWAY_ROW,    COASTAL_ROW,    GRASS_STRIP_ROW,/* 41-44 */
    CAUSEWAY_ROW,   COASTAL_ROW,     GRASS_STRIP_ROW,CAUSEWAY_ROW,   /* 45-48 */
    COASTAL_ROW,    GRASS_STRIP_ROW, CAUSEWAY_ROW,   COASTAL_ROW,    /* 49-52 */
    GRASS_STRIP_ROW,CAUSEWAY_ROW,    COASTAL_ROW,    GRASS_STRIP_ROW,/* 53-56 */
    CAUSEWAY_ROW,   COASTAL_ROW,     GRASS_STRIP_ROW,CAUSEWAY_ROW,   /* 57-60 */
    COASTAL_ROW,    GRASS_STRIP_ROW, CAUSEWAY_ROW,   COASTAL_ROW,    /* 61-64 */
    GRASS_STRIP_ROW,CAUSEWAY_ROW,    COASTAL_ROW,    GRASS_STRIP_ROW,/* 65-68 */
    CAUSEWAY_ROW,   COASTAL_ROW,     GRASS_STRIP_ROW,CAUSEWAY_ROW,   /* 69-72 */
    COASTAL_ROW,    GRASS_STRIP_ROW, CAUSEWAY_ROW,   COASTAL_ROW,    /* 73-76 */
    GRASS_STRIP_ROW,CAUSEWAY_ROW,    COASTAL_ROW,    GRASS_STRIP_ROW,/* 77-80 */
    CAUSEWAY_ROW,   COASTAL_ROW,     GRASS_STRIP_ROW,CAUSEWAY_ROW,   /* 81-84 */
    COASTAL_ROW,    GRASS_STRIP_ROW, CAUSEWAY_ROW,   COASTAL_ROW,    /* 85-88 */
    GRASS_STRIP_ROW,CAUSEWAY_ROW,    COASTAL_ROW,    GRASS_STRIP_ROW,/* 89-92 */
    CAUSEWAY_ROW,   COASTAL_ROW,     GRASS_STRIP_ROW,CAUSEWAY_ROW,   /* 93-96 */
    COASTAL_ROW,    GRASS_STRIP_ROW, CAUSEWAY_ROW,   COASTAL_ROW,    /* 97-100*/
    GRASS_STRIP_ROW,CAUSEWAY_ROW,    COASTAL_ROW,    GRASS_STRIP_ROW,/*101-104*/
    CAUSEWAY_ROW,   COASTAL_ROW,     GRASS_STRIP_ROW,CAUSEWAY_ROW,   /*105-108*/
    COASTAL_ROW,    GRASS_STRIP_ROW, CAUSEWAY_ROW,   COASTAL_ROW,    /*109-112*/
    GRASS_STRIP_ROW,CAUSEWAY_ROW,    COASTAL_ROW,    GRASS_STRIP_ROW,/*113-116*/
    CAUSEWAY_ROW,   COASTAL_ROW,     GRASS_STRIP_ROW,CAUSEWAY_ROW,   /*117-120*/
    COASTAL_ROW,    GRASS_STRIP_ROW, CAUSEWAY_ROW,   COASTAL_ROW,    /*121-124*/
    GRASS_STRIP_ROW,CAUSEWAY_ROW,    COASTAL_ROW,    GRASS_STRIP_ROW,/*125-128*/
    CAUSEWAY_ROW,   COASTAL_ROW,     GRASS_STRIP_ROW,CAUSEWAY_ROW,   /*129-132*/
    COASTAL_ROW,    GRASS_STRIP_ROW, CAUSEWAY_ROW,   COASTAL_ROW,    /*133-136*/
    GRASS_STRIP_ROW,CAUSEWAY_ROW,    COASTAL_ROW,    GRASS_STRIP_ROW,/*137-140*/
    CAUSEWAY_ROW,   COASTAL_ROW,     GRASS_STRIP_ROW,CAUSEWAY_ROW,   /*141-144*/
    COASTAL_ROW,    GRASS_STRIP_ROW, CAUSEWAY_ROW,   COASTAL_ROW,    /*145-148*/
    GRASS_STRIP_ROW,CAUSEWAY_ROW,    COASTAL_ROW,    GRASS_STRIP_ROW,/*149-152*/
    CAUSEWAY_ROW,   COASTAL_ROW,     GRASS_STRIP_ROW,CAUSEWAY_ROW,   /*153-156*/
    COASTAL_ROW,    GRASS_STRIP_ROW,                                  /*157-158*/
    TREE_ROW
};

/* =========================================================================
 * Section 3 — NE: rocky shore, grass, water
 * ========================================================================= */
const u8 world_b_section3[160 * 160] = {
    TREE_ROW,
    SHORE_ROCK_ROW, GRASS_STRIP_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /*  1-4  */
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  SHORE_ROCK_ROW, GRASS_STRIP_ROW,/*  5-8  */
    WATER_WIDE_ROW, SHORE_ROCK_ROW,  GRASS_STRIP_ROW,WATER_WIDE_ROW, /*  9-12 */
    SHORE_ROCK_ROW, GRASS_STRIP_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /* 13-16 */
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  SHORE_ROCK_ROW, GRASS_STRIP_ROW,/* 17-20 */
    WATER_WIDE_ROW, SHORE_ROCK_ROW,  GRASS_STRIP_ROW,WATER_WIDE_ROW, /* 21-24 */
    SHORE_ROCK_ROW, GRASS_STRIP_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /* 25-28 */
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  SHORE_ROCK_ROW, GRASS_STRIP_ROW,/* 29-32 */
    WATER_WIDE_ROW, SHORE_ROCK_ROW,  GRASS_STRIP_ROW,WATER_WIDE_ROW, /* 33-36 */
    SHORE_ROCK_ROW, GRASS_STRIP_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /* 37-40 */
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  SHORE_ROCK_ROW, GRASS_STRIP_ROW,/* 41-44 */
    WATER_WIDE_ROW, SHORE_ROCK_ROW,  GRASS_STRIP_ROW,WATER_WIDE_ROW, /* 45-48 */
    SHORE_ROCK_ROW, GRASS_STRIP_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /* 49-52 */
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  SHORE_ROCK_ROW, GRASS_STRIP_ROW,/* 53-56 */
    WATER_WIDE_ROW, SHORE_ROCK_ROW,  GRASS_STRIP_ROW,WATER_WIDE_ROW, /* 57-60 */
    SHORE_ROCK_ROW, GRASS_STRIP_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /* 61-64 */
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  SHORE_ROCK_ROW, GRASS_STRIP_ROW,/* 65-68 */
    WATER_WIDE_ROW, SHORE_ROCK_ROW,  GRASS_STRIP_ROW,WATER_WIDE_ROW, /* 69-72 */
    SHORE_ROCK_ROW, GRASS_STRIP_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /* 73-76 */
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  SHORE_ROCK_ROW, GRASS_STRIP_ROW,/* 77-80 */
    WATER_WIDE_ROW, SHORE_ROCK_ROW,  GRASS_STRIP_ROW,WATER_WIDE_ROW, /* 81-84 */
    SHORE_ROCK_ROW, GRASS_STRIP_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /* 85-88 */
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  SHORE_ROCK_ROW, GRASS_STRIP_ROW,/* 89-92 */
    WATER_WIDE_ROW, SHORE_ROCK_ROW,  GRASS_STRIP_ROW,WATER_WIDE_ROW, /* 93-96 */
    SHORE_ROCK_ROW, GRASS_STRIP_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /* 97-100*/
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  SHORE_ROCK_ROW, GRASS_STRIP_ROW,/*101-104*/
    WATER_WIDE_ROW, SHORE_ROCK_ROW,  GRASS_STRIP_ROW,WATER_WIDE_ROW, /*105-108*/
    SHORE_ROCK_ROW, GRASS_STRIP_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /*109-112*/
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  SHORE_ROCK_ROW, GRASS_STRIP_ROW,/*113-116*/
    WATER_WIDE_ROW, SHORE_ROCK_ROW,  GRASS_STRIP_ROW,WATER_WIDE_ROW, /*117-120*/
    SHORE_ROCK_ROW, GRASS_STRIP_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /*121-124*/
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  SHORE_ROCK_ROW, GRASS_STRIP_ROW,/*125-128*/
    WATER_WIDE_ROW, SHORE_ROCK_ROW,  GRASS_STRIP_ROW,WATER_WIDE_ROW, /*129-132*/
    SHORE_ROCK_ROW, GRASS_STRIP_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /*133-136*/
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  SHORE_ROCK_ROW, GRASS_STRIP_ROW,/*137-140*/
    WATER_WIDE_ROW, SHORE_ROCK_ROW,  GRASS_STRIP_ROW,WATER_WIDE_ROW, /*141-144*/
    SHORE_ROCK_ROW, GRASS_STRIP_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /*145-148*/
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  SHORE_ROCK_ROW, GRASS_STRIP_ROW,/*149-152*/
    WATER_WIDE_ROW, SHORE_ROCK_ROW,  GRASS_STRIP_ROW,WATER_WIDE_ROW, /*153-156*/
    SHORE_ROCK_ROW, GRASS_STRIP_ROW,                                  /*157-158*/
    TREE_ROW
};

/* =========================================================================
 * Section 4 — W: mixed water and grass
 * ========================================================================= */
const u8 world_b_section4[160 * 160] = {
    TREE_ROW,
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  COASTAL_ROW,    ISLAND_ROW,     /*  1-4  */
    WATER_WIDE_ROW, COASTAL_ROW,     ISLAND_ROW,     GRASS_STRIP_ROW,/*  5-8  */
    COASTAL_ROW,    ISLAND_ROW,      GRASS_STRIP_ROW,WATER_WIDE_ROW, /*  9-12 */
    ISLAND_ROW,     GRASS_STRIP_ROW, WATER_WIDE_ROW, COASTAL_ROW,    /* 13-16 */
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  COASTAL_ROW,    ISLAND_ROW,     /* 17-20 */
    WATER_WIDE_ROW, COASTAL_ROW,     ISLAND_ROW,     GRASS_STRIP_ROW,/* 21-24 */
    COASTAL_ROW,    ISLAND_ROW,      GRASS_STRIP_ROW,WATER_WIDE_ROW, /* 25-28 */
    ISLAND_ROW,     GRASS_STRIP_ROW, WATER_WIDE_ROW, COASTAL_ROW,    /* 29-32 */
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  COASTAL_ROW,    ISLAND_ROW,     /* 33-36 */
    WATER_WIDE_ROW, COASTAL_ROW,     ISLAND_ROW,     GRASS_STRIP_ROW,/* 37-40 */
    COASTAL_ROW,    ISLAND_ROW,      GRASS_STRIP_ROW,WATER_WIDE_ROW, /* 41-44 */
    ISLAND_ROW,     GRASS_STRIP_ROW, WATER_WIDE_ROW, COASTAL_ROW,    /* 45-48 */
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  COASTAL_ROW,    ISLAND_ROW,     /* 49-52 */
    WATER_WIDE_ROW, COASTAL_ROW,     ISLAND_ROW,     GRASS_STRIP_ROW,/* 53-56 */
    COASTAL_ROW,    ISLAND_ROW,      GRASS_STRIP_ROW,WATER_WIDE_ROW, /* 57-60 */
    ISLAND_ROW,     GRASS_STRIP_ROW, WATER_WIDE_ROW, COASTAL_ROW,    /* 61-64 */
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  COASTAL_ROW,    ISLAND_ROW,     /* 65-68 */
    WATER_WIDE_ROW, COASTAL_ROW,     ISLAND_ROW,     GRASS_STRIP_ROW,/* 69-72 */
    COASTAL_ROW,    ISLAND_ROW,      GRASS_STRIP_ROW,WATER_WIDE_ROW, /* 73-76 */
    ISLAND_ROW,     GRASS_STRIP_ROW, WATER_WIDE_ROW, COASTAL_ROW,    /* 77-80 */
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  COASTAL_ROW,    ISLAND_ROW,     /* 81-84 */
    WATER_WIDE_ROW, COASTAL_ROW,     ISLAND_ROW,     GRASS_STRIP_ROW,/* 85-88 */
    COASTAL_ROW,    ISLAND_ROW,      GRASS_STRIP_ROW,WATER_WIDE_ROW, /* 89-92 */
    ISLAND_ROW,     GRASS_STRIP_ROW, WATER_WIDE_ROW, COASTAL_ROW,    /* 93-96 */
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  COASTAL_ROW,    ISLAND_ROW,     /* 97-100*/
    WATER_WIDE_ROW, COASTAL_ROW,     ISLAND_ROW,     GRASS_STRIP_ROW,/*101-104*/
    COASTAL_ROW,    ISLAND_ROW,      GRASS_STRIP_ROW,WATER_WIDE_ROW, /*105-108*/
    ISLAND_ROW,     GRASS_STRIP_ROW, WATER_WIDE_ROW, COASTAL_ROW,    /*109-112*/
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  COASTAL_ROW,    ISLAND_ROW,     /*113-116*/
    WATER_WIDE_ROW, COASTAL_ROW,     ISLAND_ROW,     GRASS_STRIP_ROW,/*117-120*/
    COASTAL_ROW,    ISLAND_ROW,      GRASS_STRIP_ROW,WATER_WIDE_ROW, /*121-124*/
    ISLAND_ROW,     GRASS_STRIP_ROW, WATER_WIDE_ROW, COASTAL_ROW,    /*125-128*/
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  COASTAL_ROW,    ISLAND_ROW,     /*129-132*/
    WATER_WIDE_ROW, COASTAL_ROW,     ISLAND_ROW,     GRASS_STRIP_ROW,/*133-136*/
    COASTAL_ROW,    ISLAND_ROW,      GRASS_STRIP_ROW,WATER_WIDE_ROW, /*137-140*/
    ISLAND_ROW,     GRASS_STRIP_ROW, WATER_WIDE_ROW, COASTAL_ROW,    /*141-144*/
    GRASS_STRIP_ROW,WATER_WIDE_ROW,  COASTAL_ROW,    ISLAND_ROW,     /*145-148*/
    WATER_WIDE_ROW, COASTAL_ROW,     ISLAND_ROW,     GRASS_STRIP_ROW,/*149-152*/
    COASTAL_ROW,    ISLAND_ROW,      GRASS_STRIP_ROW,WATER_WIDE_ROW, /*153-156*/
    ISLAND_ROW,     GRASS_STRIP_ROW,                                  /*157-158*/
    TREE_ROW
};

/* =========================================================================
 * Section 5 — Centre: Tidecrypt sanctum entrance (ROCK ring)
 * Layout: 60 grass rows, 38 sanctum rows, 60 grass rows = 158 interior rows.
 * ========================================================================= */
const u8 world_b_section5[160 * 160] = {
    TREE_ROW,
    /* rows 1-60: approach grass */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/*  1-4  */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/*  5-8  */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/*  9-12 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/* 13-16 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/* 17-20 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/* 21-24 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/* 25-28 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/* 29-32 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/* 33-36 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/* 37-40 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/* 41-44 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/* 45-48 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/* 49-52 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/* 53-56 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/* 57-60 */
    /* rows 61-98: sanctum ring (38 rows) */
    SANCTUM_ROW,SANCTUM_ROW,SANCTUM_ROW,SANCTUM_ROW, /* 61-64 */
    SANCTUM_ROW,SANCTUM_ROW,SANCTUM_ROW,SANCTUM_ROW, /* 65-68 */
    SANCTUM_ROW,SANCTUM_ROW,SANCTUM_ROW,SANCTUM_ROW, /* 69-72 */
    SANCTUM_ROW,SANCTUM_ROW,SANCTUM_ROW,SANCTUM_ROW, /* 73-76 */
    SANCTUM_ROW,SANCTUM_ROW,SANCTUM_ROW,SANCTUM_ROW, /* 77-80 */
    SANCTUM_ROW,SANCTUM_ROW,SANCTUM_ROW,SANCTUM_ROW, /* 81-84 */
    SANCTUM_ROW,SANCTUM_ROW,SANCTUM_ROW,SANCTUM_ROW, /* 85-88 */
    SANCTUM_ROW,SANCTUM_ROW,SANCTUM_ROW,SANCTUM_ROW, /* 89-92 */
    SANCTUM_ROW,SANCTUM_ROW,SANCTUM_ROW,SANCTUM_ROW, /* 93-96 */
    SANCTUM_ROW,SANCTUM_ROW,                          /* 97-98 */
    /* rows 99-158: grass south of sanctum (60 rows) */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/* 99-102 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/*103-106 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/*107-110 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/*111-114 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/*115-118 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/*119-122 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/*123-126 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/*127-130 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/*131-134 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/*135-138 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/*139-142 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/*143-146 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/*147-150 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/*151-154 */
    GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,GRASS_STRIP_ROW,/*155-158 */
    TREE_ROW
};

/* =========================================================================
 * Section 6 — E: water and islands
 * ========================================================================= */
const u8 world_b_section6[160 * 160] = {
    TREE_ROW,
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   /*  1-4  */
    ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   ISLAND_ROW,     /*  5-8  */
    WATER_WIDE_ROW, CAUSEWAY_ROW,   ISLAND_ROW,     WATER_WIDE_ROW, /*  9-12 */
    CAUSEWAY_ROW,   ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   /* 13-16 */
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   /* 17-20 */
    ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   ISLAND_ROW,     /* 21-24 */
    WATER_WIDE_ROW, CAUSEWAY_ROW,   ISLAND_ROW,     WATER_WIDE_ROW, /* 25-28 */
    CAUSEWAY_ROW,   ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   /* 29-32 */
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   /* 33-36 */
    ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   ISLAND_ROW,     /* 37-40 */
    WATER_WIDE_ROW, CAUSEWAY_ROW,   ISLAND_ROW,     WATER_WIDE_ROW, /* 41-44 */
    CAUSEWAY_ROW,   ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   /* 45-48 */
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   /* 49-52 */
    ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   ISLAND_ROW,     /* 53-56 */
    WATER_WIDE_ROW, CAUSEWAY_ROW,   ISLAND_ROW,     WATER_WIDE_ROW, /* 57-60 */
    CAUSEWAY_ROW,   ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   /* 61-64 */
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   /* 65-68 */
    ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   ISLAND_ROW,     /* 69-72 */
    WATER_WIDE_ROW, CAUSEWAY_ROW,   ISLAND_ROW,     WATER_WIDE_ROW, /* 73-76 */
    CAUSEWAY_ROW,   ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   /* 77-80 */
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   /* 81-84 */
    ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   ISLAND_ROW,     /* 85-88 */
    WATER_WIDE_ROW, CAUSEWAY_ROW,   ISLAND_ROW,     WATER_WIDE_ROW, /* 89-92 */
    CAUSEWAY_ROW,   ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   /* 93-96 */
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   /* 97-100*/
    ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   ISLAND_ROW,     /*101-104*/
    WATER_WIDE_ROW, CAUSEWAY_ROW,   ISLAND_ROW,     WATER_WIDE_ROW, /*105-108*/
    CAUSEWAY_ROW,   ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   /*109-112*/
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   /*113-116*/
    ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   ISLAND_ROW,     /*117-120*/
    WATER_WIDE_ROW, CAUSEWAY_ROW,   ISLAND_ROW,     WATER_WIDE_ROW, /*121-124*/
    CAUSEWAY_ROW,   ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   /*125-128*/
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   /*129-132*/
    ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   ISLAND_ROW,     /*133-136*/
    WATER_WIDE_ROW, CAUSEWAY_ROW,   ISLAND_ROW,     WATER_WIDE_ROW, /*137-140*/
    CAUSEWAY_ROW,   ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   /*141-144*/
    WATER_WIDE_ROW, ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   /*145-148*/
    ISLAND_ROW,     WATER_WIDE_ROW, CAUSEWAY_ROW,   ISLAND_ROW,     /*149-152*/
    WATER_WIDE_ROW, CAUSEWAY_ROW,   ISLAND_ROW,     WATER_WIDE_ROW, /*153-156*/
    CAUSEWAY_ROW,   ISLAND_ROW,                                      /*157-158*/
    TREE_ROW
};

/* =========================================================================
 * Section 7 — SW: rocky shores and water
 * ========================================================================= */
const u8 world_b_section7[160 * 160] = {
    TREE_ROW,
    SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, /*  1-4  */
    WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, /*  5-8  */
    GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,/*  9-12 */
    SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, /* 13-16 */
    WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, /* 17-20 */
    GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,/* 21-24 */
    SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, /* 25-28 */
    WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, /* 29-32 */
    GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,/* 33-36 */
    SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, /* 37-40 */
    WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, /* 41-44 */
    GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,/* 45-48 */
    SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, /* 49-52 */
    WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, /* 53-56 */
    GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,/* 57-60 */
    SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, /* 61-64 */
    WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, /* 65-68 */
    GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,/* 69-72 */
    SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, /* 73-76 */
    WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, /* 77-80 */
    GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,/* 81-84 */
    SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, /* 85-88 */
    WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, /* 89-92 */
    GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,/* 93-96 */
    SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, /* 97-100*/
    WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, /*101-104*/
    GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,/*105-108*/
    SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, /*109-112*/
    WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, /*113-116*/
    GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,/*117-120*/
    SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, /*121-124*/
    WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, /*125-128*/
    GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,/*129-132*/
    SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, /*133-136*/
    WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, /*137-140*/
    GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,/*141-144*/
    SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, /*145-148*/
    WATER_WIDE_ROW, GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, /*149-152*/
    GRASS_STRIP_ROW,SHORE_ROCK_ROW, WATER_WIDE_ROW, GRASS_STRIP_ROW,/*153-156*/
    SHORE_ROCK_ROW, WATER_WIDE_ROW,                                  /*157-158*/
    TREE_ROW
};

/* =========================================================================
 * Section 8 — S: coastal terrain with causeway crossings
 * ========================================================================= */
const u8 world_b_section8[160 * 160] = {
    TREE_ROW,
    COASTAL_ROW,   CAUSEWAY_ROW,   COASTAL_ROW,    GRASS_STRIP_ROW, /*  1-4  */
    CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW,CAUSEWAY_ROW,    /*  5-8  */
    COASTAL_ROW,   GRASS_STRIP_ROW,CAUSEWAY_ROW,   COASTAL_ROW,     /*  9-12 */
    GRASS_STRIP_ROW,CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW, /* 13-16 */
    CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW,CAUSEWAY_ROW,    /* 17-20 */
    COASTAL_ROW,   GRASS_STRIP_ROW,CAUSEWAY_ROW,   COASTAL_ROW,     /* 21-24 */
    GRASS_STRIP_ROW,CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW, /* 25-28 */
    CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW,CAUSEWAY_ROW,    /* 29-32 */
    COASTAL_ROW,   GRASS_STRIP_ROW,CAUSEWAY_ROW,   COASTAL_ROW,     /* 33-36 */
    GRASS_STRIP_ROW,CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW, /* 37-40 */
    CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW,CAUSEWAY_ROW,    /* 41-44 */
    COASTAL_ROW,   GRASS_STRIP_ROW,CAUSEWAY_ROW,   COASTAL_ROW,     /* 45-48 */
    GRASS_STRIP_ROW,CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW, /* 49-52 */
    CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW,CAUSEWAY_ROW,    /* 53-56 */
    COASTAL_ROW,   GRASS_STRIP_ROW,CAUSEWAY_ROW,   COASTAL_ROW,     /* 57-60 */
    GRASS_STRIP_ROW,CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW, /* 61-64 */
    CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW,CAUSEWAY_ROW,    /* 65-68 */
    COASTAL_ROW,   GRASS_STRIP_ROW,CAUSEWAY_ROW,   COASTAL_ROW,     /* 69-72 */
    GRASS_STRIP_ROW,CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW, /* 73-76 */
    CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW,CAUSEWAY_ROW,    /* 77-80 */
    COASTAL_ROW,   GRASS_STRIP_ROW,CAUSEWAY_ROW,   COASTAL_ROW,     /* 81-84 */
    GRASS_STRIP_ROW,CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW, /* 85-88 */
    CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW,CAUSEWAY_ROW,    /* 89-92 */
    COASTAL_ROW,   GRASS_STRIP_ROW,CAUSEWAY_ROW,   COASTAL_ROW,     /* 93-96 */
    GRASS_STRIP_ROW,CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW, /* 97-100*/
    CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW,CAUSEWAY_ROW,    /*101-104*/
    COASTAL_ROW,   GRASS_STRIP_ROW,CAUSEWAY_ROW,   COASTAL_ROW,     /*105-108*/
    GRASS_STRIP_ROW,CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW, /*109-112*/
    CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW,CAUSEWAY_ROW,    /*113-116*/
    COASTAL_ROW,   GRASS_STRIP_ROW,CAUSEWAY_ROW,   COASTAL_ROW,     /*117-120*/
    GRASS_STRIP_ROW,CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW, /*121-124*/
    CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW,CAUSEWAY_ROW,    /*125-128*/
    COASTAL_ROW,   GRASS_STRIP_ROW,CAUSEWAY_ROW,   COASTAL_ROW,     /*129-132*/
    GRASS_STRIP_ROW,CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW, /*133-136*/
    CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW,CAUSEWAY_ROW,    /*137-140*/
    COASTAL_ROW,   GRASS_STRIP_ROW,CAUSEWAY_ROW,   COASTAL_ROW,     /*141-144*/
    GRASS_STRIP_ROW,CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW, /*145-148*/
    CAUSEWAY_ROW,  COASTAL_ROW,    GRASS_STRIP_ROW,CAUSEWAY_ROW,    /*149-152*/
    COASTAL_ROW,   GRASS_STRIP_ROW,CAUSEWAY_ROW,   COASTAL_ROW,     /*153-156*/
    GRASS_STRIP_ROW,CAUSEWAY_ROW,                                    /*157-158*/
    TREE_ROW
};

/* =========================================================================
 * Section 9 — SE: large open water with rock outcrops
 * ========================================================================= */
const u8 world_b_section9[160 * 160] = {
    TREE_ROW,
    WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, /*  1-4  */
    WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, /*  5-8  */
    SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /*  9-12 */
    WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, /* 13-16 */
    WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, /* 17-20 */
    SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /* 21-24 */
    WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, /* 25-28 */
    WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, /* 29-32 */
    SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /* 33-36 */
    WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, /* 37-40 */
    WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, /* 41-44 */
    SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /* 45-48 */
    WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, /* 49-52 */
    WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, /* 53-56 */
    SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /* 57-60 */
    WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, /* 61-64 */
    WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, /* 65-68 */
    SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /* 69-72 */
    WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, /* 73-76 */
    WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, /* 77-80 */
    SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /* 81-84 */
    WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, /* 85-88 */
    WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, /* 89-92 */
    SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /* 93-96 */
    WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, /* 97-100*/
    WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, /*101-104*/
    SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /*105-108*/
    WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, /*109-112*/
    WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, /*113-116*/
    SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /*117-120*/
    WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, /*121-124*/
    WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, /*125-128*/
    SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /*129-132*/
    WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, /*133-136*/
    WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, /*137-140*/
    SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /*141-144*/
    WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, /*145-148*/
    WATER_WIDE_ROW, SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, /*149-152*/
    SHORE_ROCK_ROW, WATER_WIDE_ROW, WATER_WIDE_ROW, SHORE_ROCK_ROW, /*153-156*/
    WATER_WIDE_ROW, WATER_WIDE_ROW,                                  /*157-158*/
    TREE_ROW
};

#undef G
#undef D
#undef W
#undef T
#undef R
